### ISSUE TITLE
ability to insert local modules

### ISSUE THREAD

**Issue by AtzeDeVries** [puppetlabs/puppetlabs-image_build#16]
Hi,

If you develop a puppet module and in combination with this project you get a lot of overhead since you have to

1. Push your code somewhwere (git / svn)
2. Change `Puppetfile` in so that docker will think there is a change
3. Wait until r10k has installed all modules

It would be easer to have a agurment for this (which can be used multipe times). Something like
`puppet docker build --add-module /path/to/your/module` and it will translate into the docker file like this
`COPY /path/to/your/module /etc/puppetlabs/code/modules/modulename`
where `modulename` is the last part of `/path/to/your/module`

this line en should be inserted before `init.pp ` is applied.

**Comment by oc243** [comment]
+1 `--modulepath` would be even better, which could point to a directory containing the modules (as is the case with vanilla `puppet apply`) that are to be copied into the container.

**Comment by garethr** [comment]
@AtzeDeVries @oc243 thanks, good suggestion. I like the idea `--modulepath` too. If anyone has time and inclination to look at a PR please do, otherwise I'll look to add this when I get a moment. Cheers

**Comment by garethr** [comment]
@AtzeDeVries @oc243 I've a PR up with this functionality at https://github.com/puppetlabs/puppetlabs-image_build/pull/27

Because the tool is implemented as a puppet subcommand we can't reuse the `modulepath` option. The current PR therefore uses `module_path` which I'm unsure about being the right option. I'd love any feedback you might have, and if you get a chance to try out and see if it addresses your needs.

**Comment by oc243** [comment]
Thanks @garethr. I'll try this out in the morning.

**Comment by oc243** [comment]
Just tried this and it seems to work well. TY!

**Comment by garethr** [comment]
Closed via #27
